version: "3.9"

name: xauusd-trading-bot

services:
  postgres:
    image: postgres:15-alpine
    container_name: trading-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: trading_db
      POSTGRES_USER: trading_bot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: trading-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "1.0.1"
    container_name: trading-bot
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # --- Runtime Mode ---
      ENVIRONMENT: production
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPATH: /app

      # --- Database ---
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: trading_bot
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      POSTGRES_DB: trading_db
      USE_SQLITE_FALLBACK: "false"

      # --- Redis ---
      REDIS_HOST: redis
      REDIS_PORT: "6379"

      # --- Logging ---
      LOG_LEVEL: INFO
      LOG_FILE: logs/trading.log

      # --- Prometheus Metrics (optional) ---
      PROMETHEUS_ENABLED: "1"
      PROMETHEUS_PORT: "8000"

      # --- Telegram (optional) ---
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN:-}
      TELEGRAM_CHAT_IDS: ${TELEGRAM_CHAT_IDS:-}

      # --- MT5 (optional; در کانتینر لینوکسی نیازمند ترمینال MT5 نیست اما کتابخانه MetaTrader5 را دارد) ---
      MT5_LOGIN: ${MT5_LOGIN:-}
      MT5_PASSWORD: ${MT5_PASSWORD:-}
      MT5_SERVER: ${MT5_SERVER:-}

      # --- AI APIs ---
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}

    ports:
      - "5000:5000"  # Flask API
      - "8000:8000"  # Prometheus metrics (اختیاری)
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
  redisdata:
